# Generated by Django 4.1.5 on 2023-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(max_length=300)),
                ("phone", models.TextField(max_length=10)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
